### PR TITLE
Maybe a little to much set

### PR DESCRIPTION
**Pull request by TApplencourt**

### CODE REVIEW

**Comment by orsinium** [comment]
I use set for alphabet because `in` operation faster for it. Letters order doesn't matter because because you can pass categories in any order. If you want sorted alphabet use this: `sorted(list(hg.Categories.get_alphabet(cats)))`

**Comment by orsinium** [comment]
Oh, sorry. Now I see. Thank you :)

**Comment by orsinium** [comment]
Please, provide description in future :)

**Comment by TApplencourt** [comment]
Yep, my bad! Been lazy is not always a good thing

**Pull request merged**
